name:                swag
version:             0.1.0.0
github:              "githubuser/swag"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/swag#readme>

dependencies:
- base >= 4.7 && < 5
- base-compat
- aeson
- aeson-pretty
- bytestring
- lens
- servant
- servant-server
- servant-swagger
- servant-swagger-ui
- servant-swagger-ui-core
- servant-swagger-ui-jensoleg >= 0.3.4
- servant-swagger-ui-redoc >= 0.3.4.1.22.3
- swagger2
- text
- time
- wai
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  swag-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - swag

tests:
  swag-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - swag
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
